### ISSUE TITLE
Bear and Cub Tokens error

### ISSUE THREAD

**Issue by kroim** [slim12kg/tokenzendr-contract#2]
truffle(development)> BEAR = BearToken.at("0x383bCF6f36Fba6B4fEADc36aDd17dB6A4DF8B0CB")
TruffleContract {
  constructor: [Function: TruffleContract] {
    _constructorMethods: {
      configureNetwork: [Function: configureNetwork],
      setProvider: [Function: setProvider],
      new: [Function: new],
      at: [AsyncFunction: at],
      deployed: [AsyncFunction: deployed],
      defaults: [Function: defaults],
      hasNetwork: [Function: hasNetwork],
      isDeployed: [Function: isDeployed],
      ... ... ...
  OwnershipRenounced: [Function],
  OwnershipTransferred: [Function],
  Approval: [Function],
  Transfer: [Function],
  sendTransaction: [Function],
  send: [Function],
  allEvents: [Function],
  getPastEvents: [Function]
}
But, the BEAR don't work
truffle(development)> BEAR.name()
Thrown:
evalmachine.<anonymous>:0
BEAR.name()
     ^

TypeError: BEAR.name is not a function
    at evalmachine.<anonymous>:0:6
    at sigintHandlersWrap (vm.js:269:15)
    at Script.runInContext (vm.js:124:14)
    at runScript (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:222:1)
    at Console.interpret (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:237:1)
    at ReplManager.interpret (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/repl.js:131:1)
    at bound (domain.js:419:14)
    at REPLServer.runBound [as eval] (domain.js:432:12)
    at REPLServer.onLine (repl.js:716:10)
    at REPLServer.emit (events.js:223:5)

**Comment by kroim** [comment]
Therefore, the test cases are failed all.
like this ...
![image](https://user-images.githubusercontent.com/33049672/74721233-06ad6e00-5272-11ea-96e0-50d0546df21f.png)

**Comment by olulofe** [comment]
@nsr-py Can you look into this issue
